name: Python

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        cd python
        python -m pipenv install --dev
    - name: Run pylint
      run: |
        cd python
        pipenv run mypy src/ tests/
    - name: Run mypy
      run: |
        cd python
        pipenv run mypy src/ tests/
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        cd python
        python -m pipenv install --dev
    - name: Discover and run all unit tests
      run: |
        cd python
        pipenv run python -m unittest discover
